### ISSUE TITLE
The video is cropped when exported if the resolution is greated than 720p

### ISSUE THREAD

**Issue by nosewad** [Picorims/wav2bar#36]
when exporting in 1920x1080, only the top left portion of the preview is exported, cutting off the rest of the video. the circle in the screenshot was centered perfectly in the preview.
![example](https://user-images.githubusercontent.com/90805307/181063073-2180a839-9225-42c6-8012-87ea99b47ee5.png)

**Comment by Picorims** [comment]
Hi,

Thank you for your report. Can you please provide the information listed below? I can't investigate anything without this information.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [e.g. 1.0.0]
 - additional specs judged useful

**Additional context**
Add any other context about the problem here.

**Comment by nosewad** [comment]
1. start wav2bar
2. edit screen resolution option to 1920 x 1080
3. export after you're done editing the video (exported video seems to be 720p, therefore only exporting the top left of the preview)

I'm on windows 10, version 21H2 (build 19044.1826)

**Comment by Lexian-droid** [comment]
Can confirm, this is indeed a problem.It only renders a portion of it, and the remaining is cut off.
